refactor: 전체적인 디자인 변경으로 구조 리펙토링 진행
mju-meetcord/Meetcord-App pull request #18
Opened 2023-05-15 07:02 UTC by jouno7201

2023-05-15 11:19 UTC, mywhzy requested changes

2023-05-15 11:19 UTC, mywhzy commented on src/components/MemberModer.tsx
> +const MemberModer = ({ isVisible, onBackdropPress }: MemberModerProps) => {
얘가 모달을 의미하는게 맞다면 아래 컴포넌트명처럼 파일 및 모든 관련 네이밍 modal로 수정 부탁드려요

2023-05-15 11:19 UTC, mywhzy commented on src/types.ts
> +export type MemberModerProps = {
얘도 모달을 의미한다면 `MemberModalProps`로 수정 부탁드립니다 :)

2023-05-15 11:47 UTC, jouno7201 commented on src/components/MemberModer.tsx
> +const MemberModer = ({ isVisible, onBackdropPress }: MemberModerProps) => {
그러네요 오타있네요

2023-05-16 05:05 UTC, mywhzy approved these changes

2023-05-16 06:36 UTC, merged